name: Serverless Deploy DEV

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Serverless Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.serverless
          key: ${{ runner.os }}-serverless-${{ hashFiles('**/serverless.yml') }}
          restore-keys: |
            ${{ runner.os }}-serverless-

      - name: Install Serverless CLI
        run: npm install -g serverless

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: serverless deploy
