name: Serverless Deploy DEV

on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Serverless Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.serverless
          key: ${{ runner.os }}-serverless-${{ hashFiles('**/serverless.yml') }}
          restore-keys: |
            ${{ runner.os }}-serverless-

      - name: Install Serverless CLI
        run: npm install -g serverless

      - name: Install npm
        run: npm install

      - name: Build Jar
        run: ./gradlew clean build

      - name: Deploy to AWS dev
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: serverless deploy --stage dev

      - name: Create Pull Request to Master
        if: success()
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: master
          pr_title: 'Merge ${{ github.ref_name }} into master'
          pr_body: 'Automated pull request to merge changes from ${{ github.ref_name }} into master.'
          pr_assignee: ''
          github_token: ${{ secrets.GITHUB_TOKEN }}
