# https://www.serverless.com/framework/docs/guides/cicd/running-in-your-own-cicd
name: Serverless Deploy PROD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Serverless Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.serverless
          key: ${{ runner.os }}-serverless-${{ hashFiles('**/serverless.yml') }}
          restore-keys: |
            ${{ runner.os }}-serverless-

      - name: Install Serverless CLI
        run: npm install -g serverless

      - name: Install npm
        run: npm install

      - name: Build Jar
        run: ./gradlew clean build

      - name: Deploy to AWS prod
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.PROD_SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        run: serverless deploy --stage prod
